//
//  FactualFieldMetadataImpl.m
//  FactualSDK
//
//  Copyright 2010 Factual Inc. All rights reserved.
//

#import "FactualFieldMetadataImpl.h"


@implementation FactualFieldMetadataImpl


// initialization 
-(id) initFromJSON:(NSDictionary*) jsonResponse {
  if (self = [super init]) {
    _fieldData = [jsonResponse retain];
  }
  return self;
}

// dealloc
-(void) dealloc {
  [_fieldData release];
  [super dealloc];
}

-(NSString*) fieldName {
  return [_fieldData objectForKey:@"name"];
}

-(NSInteger) fieldId {
  return [((NSNumber*)[_fieldData objectForKey:@"id"])intValue];
}

-(NSString*) dataType {
  return [_fieldData objectForKey:@"datatype"];
}

-(BOOL) isAutoGenerated {
  return [((NSNumber*)[_fieldData objectForKey:@"autogen"])boolValue];
}

-(BOOL) isHidden {
  return [((NSNumber*)[_fieldData objectForKey:@"hidden"])boolValue];
}

-(BOOL) isPrimary {
  return [((NSNumber*)[_fieldData objectForKey:@"isPrimary"])boolValue];
}

-(BOOL) isVotable {
  return [((NSNumber*)[_fieldData objectForKey:@"isVotable"])boolValue];
}

-(BOOL) isEnumerated {
  return [((NSNumber*)[_fieldData objectForKey:@"isEnumerated"])boolValue];
}

-(NSArray*)  enumerationList {
  return (NSArray*)[_fieldData objectForKey:@"enumerationList"];
}

-(NSString*) description {
  return [NSString stringWithFormat:@"FactualFieldMetadata fieldName:%@\tfieldId:%d\tdataType:%@\tisAutoGenerated:%d"\
          " isHidden:%d isPrimary:%d isVotable:%d isEnumerated:%d",
          [self fieldName],
          [self fieldId],
          [self dataType],
          [self isAutoGenerated],
          [self isHidden],
          [self isPrimary],
          [self isVotable],
          [self isEnumerated]];
}


@end
