//
//  FactualFieldMetadata.m
//  FactualSDK
//
//  Copyright 2010 Factual Inc. All rights reserved.
//

#import "FactualFieldMetadata.h"


@implementation FactualFieldMetadata

@dynamic fieldName;
@dynamic fieldId;
@dynamic dataType;
@dynamic isAutoGenerated;
@dynamic isHidden;
@dynamic isPrimary;
@dynamic isVotable;
@dynamic isEnumerated;
@dynamic enumerationList;

@end
